### ISSUE TITLE
Turn poll Hz and display Hz into floats

### ISSUE THREAD

**Issue by mdrejhon** [SunjunKim/mouse_cursor_simulator#2]
CPU, USB and GPU clocks are independent and can slew against each other.  360Hz may end up 360.001Hz and USB may be  7999.81Hz.  In addition, EDID may actually intentionally use a decimal Hz behind the scenes.

This creates many opportunities for many phase-slew effects that creates cyclic effects not seen with integers.   

For simplicity, mouse poll can stay as integer since display Hz varies a lot more in the real world.

- Monitors communicate plug-and-play refresh rates via EDIDs/DisplayIDs.  The numbers communicated arent often integers. Half of my 240Hz is monitors are factory-set to decimal Hz, such as 240.035Hz at the factory (or 144Hz showing as 143.996 Hz) because of signal timing mathematics.
- Legacy timing standards such NTSC 59.94Hz which are also part of my 1920x1080p 59.94Hz EDID (shows up as "59Hz" in Control Panel).  I have seen 119.88 Hz and occasionally 239.76 Hz in the EDID's of various 240Hz monitors, strange as it may be.

**Comment by SunjunKim** [comment]
Solved
